INSERT INTO tipo (descricao) VALUES
  ('Cachorro'),
	('Gato'),
	('Equino');

INSERT INTO raca (descricao) VALUES
	('Abissínio'),
	('Akita Inu'),
	('American Pitbull Terrier'),
	('Andaluz'),
	('Angorá'),
	('Australian Cattle Dog (Blue Heeler)'),
	('Bassethound'),
	('Beagle'),
	('Beagle Mestiço'),
	('Bengali'),
	('Bernese Mountain Dog'),
	('Border Collie'),
	('Boxer'),
	('Bretão'),
	('British Shorthair'),
	('Bulldog Americano'),
	('Bulldog Francês'),
	('Bulldog Inglês'),
	('Chihuahua'),
	('Chow Chow'),
	('Cocker Spaniel Americano'),
	('Cocker Spaniel Ingles'),
	('Dachshund (Teckel)'),
	('Dálmata'),
	('Dobermann Pinshcer'),
	('Dogue Alemão'),
	('Exótica'),
	('Fila Brasileiro'),
	('Fox Paulistinha Mestiço'),
	('Golden Retriever'),
	('Husky Siberiano'),
	('Irish Soft Coated Wheaten Terr'),
	('Jack Russel Terrier'),
	('Labrador (Retriever do)'),
	('Labrador Mestiço'),
	('Lhasa-Apso'),
	('Maine Coon'),
	('Maltês'),
	('Mangalarga'),
	('Mastiff Inglês'),
	('Papillon'),
	('Pastor Alemão'),
	('Pastor Alemão Mestiço'),
	('Pastor Belga'),
	('Pastor Catalão'),
	('Pastor de Shetland'),
	('Pequeno Lebrel Italiano'),
	('Pequinês'),
	('Persa'),
	('Pinscher'),
	('Pitbull (American Pitbull Terrier)'),
	('Pitbull Mestiço'),
	('Pointer Inglês'),
	('Poodle Mestiço'),
	('Poodle Micro'),
	('Poodle Toy'),
	('Pug'),
	('Ragdoll'),
	('Retriever do Labrador'),
	('Rottweiler'),
	('Rottweiler Mestiço'),
	('Russian Blue'),
	('Sagrado da Birmania'),
	('Schipperke'),
	('Schnauzer Miniatura'),
	('Shiba Inu'),
	('Shih Tzu'),
	('Siamês'),
	('Siamês Mix'),
	('Singapura'),
	('Spitz Alemão'),
	('SRD'),
	('Teckel (Dachshund)'),
	('Terrier Brasileiro'),
	('Toy Fox Terrier'),
	('Veadeiro Brasileiro'),
	('Weimaraner'),
	('West Highland White Terrier'),
	('Yorkshire');

INSERT INTO porte (descricao) VALUES
	('Pequeno'),
	('Médio'),
	('Grande');

INSERT INTO cor (descricao) VALUES
	('Abricot'),
	('Acaju'),
	('Alazão'),
	('Amarelo'),
	('Amarelo e Branco'),
	('Amarelo e Preto'),
	('Azul'),
	('Azul Aco'),
	('Azul Mosqueado'),
	('Azul Ruão'),
	('Bege'),
	('Bege e Branco'),
	('Bege e Marrom'),
	('Bege e Preto'),
	('Branco'),
	('Branco Pirata'),
	('Branco e Amarelo'),
	('Branco e Bege'),
	('Branco e Caramelo'),
	('Branco e Castanho'),
	('Branco e Chocolate'),
	('Branco e Cinza'),
	('Branco e Cinza Tigrado'),
	('Branco e Creme'),
	('Branco e Dourado'),
	('Branco e Laranja'),
	('Branco e Marrom'),
	('Branco e Marron'),
	('Branco e Mel'),
	('Branco e Preto'),
	('Canela e Preto'),
	('Caramelo'),
	('Caramelo Claro'),
	('Caramelo e Branco'),
	('Caramelo e Preto'),
	('Castanho'),
	('Castanho Escuro'),
	('Castanho Prateado'),
	('Chocolate'),
	('Cinza'),
	('Cinza Escuro Tigrado'),
	('Cinza Pardo e Marrom'),
	('Cinza Tigrado'),
	('Cinza Tigrado e Branco'),
	('Cinza e Branco'),
	('Cinza e Creme'),
	('Creme'),
	('Creme e Cinza'),
	('Creme e Marrom'),
	('Dourado'),
	('Dourado e Branco'),
	('Fulvo'),
	('Fulvo Encarvoado'),
	('Fígado Ruão'),
	('Laranja e Branco'),
	('Marrom'),
	('Marrom Claro'),
	('Marrom Escuro'),
	('Marrom e Branco'),
	('Marrom e Cinza'),
	('Marrom e Preto'),
	('Marrom e Preto Tigrado'),
	('Preto'),
	('Preto e Amarelo'),
	('Preto e Bege'),
	('Preto e Branco'),
	('Preto e Canela'),
	('Preto e Caramelo'),
	('Preto e Castanho'),
	('Preto e Castanho Claro'),
	('Preto e Marrom'),
	('Tordilho'),
	('Trigueiro');

INSERT INTO comprimento_pelo (descricao) VALUES
	('Sem pelo'),
	('Curto'),
	('Médio'),
	('Longo');

INSERT INTO localizacao (bairro, cidade, uf) VALUES
  ('Centro', 'São Francisco do Sul', 'SC'),
  ('Floresta', 'Joinville', 'SC');

INSERT INTO pet (id_comprimento_pelo, id_cor, id_localizacao, id_porte, id_raca, id_tipo) VALUES
  (1, 1, 1, 1, 1, 1),
  (2, 2, 2, 2, 2, 2),
  (3, 3, 1, 3, 3, 3);
